# Generated by Django 5.2.4 on 2025-08-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organiser_email',
            field=models.EmailField(blank=True, help_text='Organiser email', max_length=254),
        ),
    ]
