# Generated by Django 5.2.4 on 2025-07-26 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_signup_user'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE UNIQUE INDEX signup_user_event_unique ON signup_signup (user_id, event_id) WHERE user_id IS NOT NULL;",
            reverse_sql="DROP INDEX IF EXISTS signup_user_event_unique;",
        ),
    ]
