# Generated by Django 5.2.4 on 2025-08-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_event_organiser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubuser',
            name='ea_urn',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
