# Generated by Django 5.2.4 on 2025-08-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_alter_clubuser_ea_urn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubuser',
            name='ea_urn',
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='preregistration',
            name='ea_urn',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
