# Generated by Django 5.2.4 on 2025-08-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_alter_clubuser_ea_urn_alter_preregistration_ea_urn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preregistration',
            name='ea_urn',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
