# Generated by Django 5.2.4 on 2025-08-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_pendingverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingverification',
            name='verified_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
