# Generated by Django 5.2.4 on 2025-08-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0007_pendingverification_verified_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregistration',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
