# Generated by Django 5.2.4 on 2025-08-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0008_preregistration_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participants_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='reminder_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
